services:
  redis:
    image: redis:7-alpine
    container_name: rlt-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: rlt-backend
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: rlt-frontend
    ports:
      - "4173:4173"
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_WS_URL=ws://localhost:3001
